aplicacao/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager



class ImageCarousel(models.Model):
    image = models.ImageField(upload_to='carousel_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.caption if self.caption else "Carousel Image"


#Carrossel de Imagens
    
class ImgCarrossel(models.Model):
    image1 = models.ImageField(upload_to='carousel_images/')
    image2 = models.ImageField(upload_to='carousel_images/')
    image3 = models.ImageField(upload_to='carousel_images/')
    
    
#Eletivas   

class Eletiva(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='ele_images/')

    def __str__(self):
        return self.title

# Link inscrever nas eletivas

class LinkEletiva(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()    
    
    def __str__(self):
        return self.title
    
# Tutoria

class Tutoria(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='tutoria_images/')
    
    def __str__(self):
        return self.title
    
# Links
class SocialLinks(models.Model):
    instagram_url = models.URLField(max_length=255, blank=True, null=True)
    whatsapp_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"Instagram: {self.instagram_url}, WhatsApp: {self.whatsapp_number}"

# Mais Sobre
class MaisSobre(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='mais_images/', null=True)
    image_2 = models.ImageField(upload_to='mais_images/', null=True)
    image_3 = models.ImageField(upload_to='mais_images/', null=True)

    def __str__(self):
        return self.title
    
# Calendário



# Nossa História

class Historia(models.Model):
    nome = models.CharField(max_length=255)
    data = models.DateField()
    imagem = models.ImageField(upload_to='imagens/')

    def __str__(self):
        return self.nome

    
class NewsOne(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    description_2 = models.TextField()
    image = models.ImageField(upload_to='news_images/', null=True)
    date_published = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

class Noticia2(models.Model):
    titulo = models.CharField(max_length=200)
    descricao1 = models.TextField()
    descricao2 = models.TextField()
    imagem = models.ImageField(upload_to='news_images/')
    data_publicacao = models.DateField()

    def __str__(self):
        return self.titulo

class Noticia3(models.Model):
    title = models.CharField(max_length=255)
    description1 = models.TextField()
    description2 = models.TextField()
    image = models.ImageField(upload_to='news_images/')
    data_publicacao = models.DateField()
    

class Evento(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    data = models.TextField(null=True)
    hora = models.TimeField()

    def __str__(self):
        return self.nome

class Integrado(models.Model):
    nome_semana = models.CharField(max_length=50)
    foto_cardapio = models.ImageField(upload_to='fotos_cardapio/')
    nome_comida = models.CharField(max_length=100)
    data_cardapio = models.DateField()

    def __str__(self):
        return f'{self.nome_semana} - {self.nome_comida}'

    class Meta:
        verbose_name = 'Cardápio Integrado'
        verbose_name_plural = 'Cardápios Integrados'

class RegularLanche(models.Model):
    nome_dia_semana = models.CharField(max_length=20)  # Nome do dia da semana (e.g. Segunda-feira)
    nome_comida = models.CharField(max_length=100)  # Nome da comida
    imagem = models.ImageField(upload_to='lanche_imagens/')  # Campo de imagem
    data_cardapio = models.DateField()  # Data do cardápio

    def __str__(self):
        return f"{self.nome_dia_semana}: {self.nome_comida} ({self.data_cardapio})"


class RegularAlmoco(models.Model):
    dia_da_semana = models.CharField(max_length=100, null=True)  # Ex: 'Segunda'
    nome_da_comida = models.CharField(max_length=100)  # Ex: 'Arroz com Feijão'
    imagem = models.ImageField(upload_to='imagens/')  # Ex: 'imagem.jpg'
    data_do_cardapio = models.DateField()  # Ex: '2024-10-22'

    def __str__(self):
        return f"{self.dia_da_semana} - {self.nome_da_comida}"

class Eja(models.Model):
    dia_da_semana = models.CharField(max_length=100)
    nome_da_comida = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='imagens/')
    data_do_cardapio = models.DateField()
    
    def __str__(self):
        return f"{self.dia_da_semana} - {self.nome_da_comida}"
    
class DiretorManager(BaseUserManager):
    def create_diretor(self, nome, email, senha=None):
        if not email:
            raise ValueError("O campo email é obrigatório")
        diretor = self.model(nome=nome, email=self.normalize_email(email))
        diretor.set_password(senha)
        diretor.save(using=self._db)
        return diretor

class Diretor(AbstractBaseUser):
    nome = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    
    objects = DiretorManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    def __str__(self):
        return self.nome

aplicacao/templates/noticia2/adicionar_noticia.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Notícia 2</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'cardapio/adicionar.css' %}">
    <link rel="stylesheet" href="{% static 'adicionar.css' %}">
</head>
<body>
    <section class="wrapper">
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>
    </section>
    <div class="container">
        <div class="form-container">
            <h1>Adicionar Notícia 2</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nome_semana">Título</label>
                    {{ form.titulo }}
                </div>

                <div class="form-group">
                    <label for="id_foto_cardapio">Imagem</label>
                    {{ form.imagem }}
                </div>

                <div class="form-group">
                    <label for="id_nome_comida">Descrição</label>
                    {{ form.descricao1 }}
                </div>

                <div class="form-group">
                    <label for="id_data_cardapio">Descrição</label>
                    {{ form.descricao2 }}
                </div>
                <div class="form-group">
                    <label for="id_data_cardapio">Data</label>
                    {{ form.data_publicacao }}
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn-primary">Salvar</button>
                    <a href="{% url 'area_diretor' %}" class="btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
    <div class="cursor"></div>
   <script>
     // script.js
    
     const cursor = document.querySelector('.cursor');
    
     // Função para ativar o efeito de movimento do cursor
     document.addEventListener('mousemove', (e) => {
       cursor.style.left = `${e.pageX}px`;
       cursor.style.top = `${e.pageY}px`;
       cursor.classList.add('active'); // Adiciona a classe 'active' para aumentar o cursor
    
       // Reseta a classe 'inactive' quando o mouse está em movimento
       cursor.classList.remove('inactive');
       cursor.classList.remove('out');
    
       // Reinicia o temporizador de inatividade
       resetInactiveTimer();
     });
    
     // Função para esconder o cursor ao sair da janela
     document.addEventListener('mouseout', () => {
       cursor.classList.add('out'); // Adiciona a classe 'out' para esconder o cursor
     });
    
     // Timer para identificar inatividade do mouse
     let inactiveTimer;
    
     function resetInactiveTimer() {
       clearTimeout(inactiveTimer);
       inactiveTimer = setTimeout(() => {
         cursor.classList.add('inactive'); // Adiciona a classe 'inactive' quando o mouse para
       }, 1000); // 1 segundo de inatividade
     }
   </script>
</body>
</html>

aplicacao/templates/noticia2/apagar_noticia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Tem certeza que deseja apagar a notícia "{{ noticia.titulo }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Apagar</button>
    <a href="{% url 'home' %}">Cancelar</a>
</form>

</body>
</html>

aplicacao/templates/noticia2/editar_noticia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

aplicacao/templates/noticia2/view_news_two.html
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Visualizar noticia</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   {% load static %}
    <link rel="stylesheet" href="{% static 'visualizar_noticias.css' %}">
</head>
<body>
    <header class="header-noticia">
        <div class="blue-section">
            <h1 class="topo-asn">EEEFM ANTONIO DOS SANTOS NEVES</h1>
            <img class="logo" src="https://images.sympla.com.br/65087b3baa195-lg.png" alt="Logo">
        </div>
        <div class="yellow-section">
            <a class="inicio" href="{% url 'home' %}"><i class="bi bi-house"></i>Inicio</a>
        </div>
    </header>
   <div class="completa-noticia">
     <div class="noticia">
       <h1 class="titulo-noticia">{{ noticia.titulo }}</h1>
       <div class="data-buttons">
        <div class="data">
            <i class="far fa-calendar-alt"></i>
            <span>Publicado em {{ noticia.data_publicacao }}</span>
        </div>
        <div class="social-buttons">
            <a href="" class="instagram-button"><i class="fab fa-instagram"></i></a>
            <a href="" class="facebook-button"><i class="fab fa-facebook"></i></a>
        </div>
       </div>

       <hr class="linha"> <!-- Linha horizontal -->
       
       <img class="img-noticia" src="{{ noticia.imagem.url }}" style="width: 60%;" >
             
       
       <p class="descricao-noticia" style="font-size: 1.5em;">{{ noticia.descricao1 }}</p>
       <p class="descricao-noticia" style="font-size: 1.5em;">{{ noticia.descricao2 }}</p>
     </div>
    </div>
    <footer class="custom-footer bg-body-tertiary text-center text-lg-start">
        <div class="footer-bar">
            <div class="footer-container">
                <div class="footer-logo">
                    <img src="https://images.sympla.com.br/65087b3baa195-lg.png" alt="ASN Logo" style="width: 10%;" />
                </div>
                <div class="footer-social">
                    <a href="#"><i class="bi bi-instagram" id="instagram"></i></a>
                    <a href="#"><i class="bi bi-tiktok" id="tiktok"></i></a>
                    <a href="#"><i class="bi bi-youtube" id="youtube"></i></a>
                    <a href="#"><i class="bi bi-twitter" id="twitter"></i></a>
                </div>
                <div class="footer-info">
                    <p><strong>ANTONIO DOS SANTOS NEVES (ASN)</strong></p>
                    <p>Avenida Democrata - Centro</p>
                    <p>CEP: 29845-000 - Boa Esperança - ES</p>
                    <p>Tel: (27) 1234-5678</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>