aplicacao/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager



class ImageCarousel(models.Model):
    image = models.ImageField(upload_to='carousel_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.caption if self.caption else "Carousel Image"


#Carrossel de Imagens
    
class ImgCarrossel(models.Model):
    image1 = models.ImageField(upload_to='carousel_images/')
    image2 = models.ImageField(upload_to='carousel_images/')
    image3 = models.ImageField(upload_to='carousel_images/')
    
    
#Eletivas   

class Eletiva(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='ele_images/')

    def __str__(self):
        return self.title

# Link inscrever nas eletivas

class LinkEletiva(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()    
    
    def __str__(self):
        return self.title
    
# Tutoria

class Tutoria(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='tutoria_images/')
    
    def __str__(self):
        return self.title
    
# Links
class SocialLinks(models.Model):
    instagram_url = models.URLField(max_length=255, blank=True, null=True)
    whatsapp_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"Instagram: {self.instagram_url}, WhatsApp: {self.whatsapp_number}"

# Mais Sobre
class MaisSobre(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='mais_images/', null=True)
    image_2 = models.ImageField(upload_to='mais_images/', null=True)
    image_3 = models.ImageField(upload_to='mais_images/', null=True)

    def __str__(self):
        return self.title
    
# Calendário



# Nossa História

class Historia(models.Model):
    nome = models.CharField(max_length=255)
    data = models.DateField()
    imagem = models.ImageField(upload_to='imagens/')

    def __str__(self):
        return self.nome

    
class NewsOne(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    description_2 = models.TextField()
    image = models.ImageField(upload_to='news_images/', null=True)
    date_published = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

class Noticia2(models.Model):
    titulo = models.CharField(max_length=200)
    descricao1 = models.TextField()
    descricao2 = models.TextField()
    imagem = models.ImageField(upload_to='news_images/')
    data_publicacao = models.DateField()

    def __str__(self):
        return self.titulo

class Noticia3(models.Model):
    title = models.CharField(max_length=255)
    description1 = models.TextField()
    description2 = models.TextField()
    image = models.ImageField(upload_to='news_images/')
    data_publicacao = models.DateField()
    

class Evento(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    data = models.TextField(null=True)
    hora = models.TimeField()

    def __str__(self):
        return self.nome

class Integrado(models.Model):
    nome_semana = models.CharField(max_length=50)
    foto_cardapio = models.ImageField(upload_to='fotos_cardapio/')
    nome_comida = models.CharField(max_length=100)
    data_cardapio = models.DateField()

    def __str__(self):
        return f'{self.nome_semana} - {self.nome_comida}'

    class Meta:
        verbose_name = 'Cardápio Integrado'
        verbose_name_plural = 'Cardápios Integrados'

class RegularLanche(models.Model):
    nome_dia_semana = models.CharField(max_length=20)  # Nome do dia da semana (e.g. Segunda-feira)
    nome_comida = models.CharField(max_length=100)  # Nome da comida
    imagem = models.ImageField(upload_to='lanche_imagens/')  # Campo de imagem
    data_cardapio = models.DateField()  # Data do cardápio

    def __str__(self):
        return f"{self.nome_dia_semana}: {self.nome_comida} ({self.data_cardapio})"


class RegularAlmoco(models.Model):
    dia_da_semana = models.CharField(max_length=100, null=True)  # Ex: 'Segunda'
    nome_da_comida = models.CharField(max_length=100)  # Ex: 'Arroz com Feijão'
    imagem = models.ImageField(upload_to='imagens/')  # Ex: 'imagem.jpg'
    data_do_cardapio = models.DateField()  # Ex: '2024-10-22'

    def __str__(self):
        return f"{self.dia_da_semana} - {self.nome_da_comida}"

class Eja(models.Model):
    dia_da_semana = models.CharField(max_length=100)
    nome_da_comida = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='imagens/')
    data_do_cardapio = models.DateField()
    
    def __str__(self):
        return f"{self.dia_da_semana} - {self.nome_da_comida}"
    
class DiretorManager(BaseUserManager):
    def create_diretor(self, nome, email, senha=None):
        if not email:
            raise ValueError("O campo email é obrigatório")
        diretor = self.model(nome=nome, email=self.normalize_email(email))
        diretor.set_password(senha)
        diretor.save(using=self._db)
        return diretor

class Diretor(AbstractBaseUser):
    nome = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    
    objects = DiretorManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    def __str__(self):
        return self.nome

aplicacao/templates/eletivas/add_link_eletivas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
</body>
</html>

aplicacao/templates/eletivas/adicionar_eletivas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'adicionar_eletivas.css' %}">
    <link rel="stylesheet" href="{% static 'adicionar.css' %}">
</head>
<body>
    <div class="card">
        <h2>Adicionar Eletivas</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Título:</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label for="id_sub_title">Sub-título:</label>
                {{form.sub_title}}
            </div>
            <div class="form-group">
                <label for="id_description">Descrição:</label>
                {{form.description}}
            </div>
            <div class="form-group">
                <label for="id_image">Imagem:</label>
                {{form.image}}
            </div>
            <button type="submit">Salvar</button>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const imageInput = document.querySelector('input[type="file"]');
            const previewImage = document.getElementById('preview-image');

            imageInput.addEventListener('change', function(event) {
                const file = event.target.files[0];
                if (file) {
                    const reader = new FileReader();
                    reader.onload = function(e) {
                        previewImage.src = e.target.result;
                        previewImage.style.display = 'block';
                    }
                    reader.readAsDataURL(file);
                } else {
                    previewImage.style.display = 'none';
                }
            });
        });
    </script>
</body>
</html>

aplicacao/templates/eletivas/apagar_eletivas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apagar Eletiva</title>
</head>
<body>
    <h1>Apagar Eletivas</h1>
    <p>Tem certeza que deseja apagar a notícia "{{ eletiva.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
        <a href="{% url 'lista' %}">Cancelar</a>
    </form>
</body>
</html>

aplicacao/templates/eletivas/apagar_link_eletivas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apagar Notícia</title>
</head>
<body>
    <h1>Apagar Link Eletivas</h1>
    <p>Tem certeza que deseja apagar a notícia "{{ links.link }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmar</button>
        <a href="{% url 'lista' %}">Cancelar</a>
    </form>
</body>
</html>

aplicacao/templates/eletivas/lista.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Lista de Eletivas</title>
 <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
 {% load static %}
 <link rel="stylesheet" href="{% static 'eletivas/tutoria_eletivas.css' %}">
</head>
<body>
   <header class="topo">
       <div class="secondary-bar secondary-bar-top">
           <div class="parallelogram parallelogram-1"></div>
       </div>
       <div class="blue-1"></div>
       <div class="blue"></div>
       <div class="triangulo"></div>
       <div class="triangulo-2"></div>
       <h1 class="topo-asn">EEEFM ANTONIO DOS SANTOS NEVES</h1>
       <img class="logo" src="https://images.sympla.com.br/65087b3baa195-lg.png" alt="Logo">
       <div class="blue-2"></div>
       <div class="yellow-section">
          
        {% for links in link %}
        <button type="button" class="btn btn-outline-primary"><a href="{{links.link}}">{{links.title}}</a></button>
        <a href="{% url 'apagar_link_eletivas' links.id %}">Apagar</a>
        {% endfor %}
          
           <a class="inicio" href="{% url 'mais_sobre' %}"><i class="bi bi-chat-square-text"></i></i>Mais sobre</a>
           <a class="inicio" href="{% url 'home' %}"><i class="bi bi-house"></i>Inicio</a>
       </div>
   </header>


   <div class="slide-container">
       <div class="slide-content">
           <div class="card-wrapper">
             {% for eletiva in eletivas %}
             <div class="card">
                 <div class="image-content">
                     <span class="overlay"></span>
                     <div class="card-image">
                         <img src="{{ eletiva.image.url }}" class="card-img">
                     </div>
                 </div>
                 <div class="card-content" style="font-family: Arial, Helvetica, sans-serif;">
                     <h2 class="name">{{ eletiva.title }}</h2>
                     <p class="sub-titulo">{{ eletiva.sub_title }}</p>
                     <a class="ver" href="{% url 'view_eletivas' eletiva.id %}" style="text-decoration: none;">Ver mais</a>
                 </div>
             </div>
             {% endfor %}
            </div>
       </div>
   </div>
 
 
 <footer class="custom-footer bg-body-tertiary text-center text-lg-start">
   <div class="secondary-bar-rodape">
       <div class="parallelogram-rodape"></div>
   </div>
   <div class="blue-2-footer" ></div>
       <div class="blue-footer" ></div>
   <div class="yellow-section-footer"></div>
   <div class="footer-bar">
       <div class="footer-container">
           <div class="footer-logo">
               <img src="https://images.sympla.com.br/65087b3baa195-lg.png" alt="ASN Logo" style="width: 8%;" />
           </div>
           <div class="footer-social">
               <a href="#"><i class="bi bi-instagram" id="instagram"></i></a>
               <a href="#"><i class="bi bi-whatsapp" id="whatsapp"></i></a>
           </div>
           <div class="footer-info">
               <p><strong>ANTONIO DOS SANTOS NEVES (ASN)</strong></p>
               <p>Avenida Democrata - Centro</p>
               <p>CEP: 29845-000 - Boa Esperança - ES</p>
               <p>Tel: (27) 1234-5678</p>
           </div>
       </div>
   </div>
</footer>


</body>
</html>

aplicacao/templates/eletivas/view_eletivas.html
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Visualizar eletivas</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   {% load static %}
    <link rel="stylesheet" href="{% static 'ver_eletivas.css' %}">
   <style>
       * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body{
            background-color: #fff;
        }
        .header-noticia {
            width: 100%;
            height: 100vh;
            position: relative;
        }

        .blue-section {
            background-color: #005bbb;
            height: 20%;
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 1rem;
            position: relative;
            z-index: 1;
        }

        .blue-section .topo-asn {
            color: #fff;
            font-size: 1.5rem; /* Adjust the font size as needed */
            text-align: center; /* Center text horizontally */
            flex-grow: 1; /* Allow text to grow and occupy available space */
        }

        .blue-section .logo {
            width: 130px; /* Set the logo size */
            height: auto; /* Maintain aspect ratio */
            margin-top: 20px; /* Adjust this value to lower the image */
        }

        .yellow-section {
            background-color: #ffd500;
            height: 8%;
            width: 62%;
            position: absolute;
    top: 20%;
    right: 0;
    clip-path: polygon(100% 0%, 100% 100%, 7% 100%, 0% 0%);
    display: flex;
    align-items: center;
    justify-content: flex-end; /* Alinha o conteúdo à direita */
    padding: 0 1rem;
    z-index: 1;
        }
        .inicio {
    font-size: 20px; /* Ajuste o tamanho da fonte conforme necessário */
    color: #fff; /* Cor do texto */
    text-decoration: none; /* Remove o sublinhado */
    display: flex;
    align-items: center;
}

.inicio i {
    margin-right: 8px; /* Espaço entre o ícone e o texto */
    width: 20px;
}

.inicio:hover {
    color: #003d7a; /* Cor do texto ao passar o mouse */
}

       .completa-eletivas {
           width: 100%;
           margin: auto;
           position: absolute;
           top: 40%;
           display: flex;
           justify-content: center;
           align-items: center;
    
       }

       .eletivas-card {
           width: 50%;
           padding: 20px; /* Espaçamento interno para melhorar visualização */
           display: flex;
           flex-direction: column; /* Organiza os itens verticalmente */
       }

       .eletivas-card .titulo-eletivas .sub-eletivas{
           margin-bottom: 20px;
           font-size: 1.5rem; /* Tamanho do título */
           color: #333; /* Cor do texto */
           
       }
       
       .linha-eletivas {
           width: 100%;
           margin: 20px 0;
           border-top: 1px solid #ccc;
       }

       .descricao-eletivas {
           font-family: helvetica;
           text-align: justify;
           margin-top: 30px;
           margin-bottom: 20px; /* Espaçamento inferior */
       }

       .img-eletivas {
           width: 50%;
           height: auto;
           display: block;
           margin: auto;
           margin-top: 40px; /* Espaçamento superior */
           margin-bottom: 40px; /* Espaçamento inferior */
       }

       @media (max-width: 700px) {
           .eletivas-card {
               width: 95%;
           }
           .yellow-section {
                width: 100%;
                clip-path: polygon(100% 0%, 100% 100%, 0% 100%, 0% 0%);
            }
       }
        
   </style>
</head>
<body>
    <header class="header-noticia">
        <div class="blue-section">
            <h1 class="topo-asn">EEEFM ANTONIO DOS SANTOS NEVES</h1>
            <img class="logo" src="https://images.sympla.com.br/65087b3baa195-lg.png" alt="Logo">
        </div>
        <div class="yellow-section">
            <a class="inicio" href="{% url 'lista' %}"><i class="bi bi-house"></i>Eletivas</a>
        </div>
    </header>
   <div class="completa-eletivas">
     <div class="eletivas-card">
       <h1 class="titulo-eletivaa">{{ eletiva.title }}</h1>

       <hr class="linha-eletivas"> <!-- Linha horizontal -->
       
       <img class="img-eletivas" src="{{ eletiva.image.url }}">
             
       <h1 class="sub-eletivas">{{ eletiva.sub_title }}</h1>
       <p class="descricao-eletivas">{{ eletiva.description }}</p>
     </div>
    </div>
</body>
</html>